name: "Create Repository Secrets in Sub-Repo"

on:
  push:
    branches:
      - main  # Runs when new code is pushed to main

permissions:
  actions: write  # Allows creating repository secrets
  contents: read  # Allows reading repo content

jobs:
  create-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install PyGithub

      - name: Run Secret Creation Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use a PAT with repo & secrets access
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}  # Fixes incorrect repo name issue
        run: python create_secrets.py

